  name: Deploy to Firebase Hosting

  on:
    push:
      branches:
        - main  # or your preferred branch

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.18.0'  # specify the version

        - name: Install dependencies
          run: npm ci

        - name: Build Astro app
          run: npm run build

        - name: Deploy to Firebase Hosting
          run: firebase deploy --only hosting
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

